# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Matta5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Matta5
  pod 'GoogleMaps', '4.1.0'
  pod 'GooglePlaces', '4.1.0'

  target 'Matta5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Matta5UITests' do
    # Pods for testing
  end

end
